### ISSUE TITLE
Student able to send work ticket (Design and function)

### ISSUE THREAD

**Issue by JamesFong1027** [JamesFong1027/BatonMeteor#17]

**Comment by VictorChenLi** [comment]
Do we need worry that student would keep sending big number ticket in order to get teacher's attention. 

Could we use something like talk ticket (conception problem, need tips, question about work, confuse, etc) or number is more important than that

Or we give student a total number credit, like the total number they send through work ticket shouldn't over certain number. So they will use it wisely

**Comment by ZT83** [comment]
Can't limit their requests, i.e. "Credits" can't be the solution. It's a smart ideas, but would cause lots of controversy and backlash as students are supposed to feel like they can ALWAYS ask for help.

**Comment by ZT83** [comment]
I think we start with a number, and we test from there. It's true that students could "game" the system, but we want to see if that actually IS an issue, before trying to solve for it.

**Comment by ZT83** [comment]
Maybe we offer the choice to teachers...don't limit them.  They can use a credit system or they can leave it unlimited.
